server:
  ssl:
    enabled: true
    key-store: "${posisi_key_store}"
    key-store-password: "${key_store_passwd}"
    key-alias: "${key_alias}"
    key-store-type: "${key_store_type}"
    trust-store: "${posisi_trust_store}"
    trust-store-password: "${trust_store_passwd}"
    client-auth: "need"
  port: 8089
  servlet:
    context-path: "/singserver/rest/v1"

spring:
  main: 
    banner-mode: "off"
    #web-application-type: none
  activemq:
    broker-url:tcp://127.0.0.1:61616
    
camel:
  springboot:
    :main-run-controller: true

security.enable-csrf: ${enable_csrf}