server:
  ssl:
    enabled: true
    key-store: "${posisi-key-store}"
    key-store-password: "${key-store-passwd}"
    key-alias: "${key-alias}"
    key-store-type: "${key-store-type}"
    trust-store: "${posisi-trust-store}"
    trust-store-password: "${trust-store-passwd}"
    client-auth: "need"
  port: 8089
  servlet:
    context-path: "/singserver/rest/v1"

spring:
  main: 
    banner-mode: "off"
  activemq:
    broker-url:tcp://127.0.0.1:61616
    
camel:
  springboot:
    :main-run-controller: true

security.enable-csrf: ${enable-csrf}